name: Production Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: DEPLOY
    runs-on: ubuntu-18.04
  
    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Call AWS CodeDeploy
      run: |
        aws deploy create-deployment \
          --region ap-northeast-2 \
          --application-name zennbot-deploy \
          --deployment-group-name zennbot-deploy-group \
          --github-location repository="zennvote/zennvote-backend-v3",commitId="${{ github.sha }}"